name: Upload Maps to S3
on:
  push
  # push:
  #   branches: [ master ]

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  UploadMapsToS3:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: ghamapuploadingrolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload maps to S3
        run: aws s3 cp --recursive ./_maps/. s3://${{ secrets.S3_BUCKET_NAME }}/cswt/Maps

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths /cswt/Maps/*
